grid_map_topic: /grid_map

grid_map_visualizations:

  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation

  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: elevation
     data_min: -1
     data_max: 1

  - name: normals
    type: vectors
    params:
     layer_prefix: normal_
     position_layer: elevation
     scale: 0.06
     line_width: 0.005
     color: 15600153

  - name: slope
    type: occupancy_grid
    params:
     layer: slope
     data_min: -90.0
     data_max: 90.0

  - name: step_height
    type: occupancy_grid
    params:
     layer: rel_height
     data_min: -10.0
     data_max: 10.0

  - name: obstacle
    type: occupancy_grid
    params:
     layer: obstacle
     data_min: 0.0
     data_max: 1.0

  - name: obstacle_potential_field
    type: occupancy_grid
    params:
     layer: obstacle_with_pf
     data_min: 0.0
     data_max: 1.0

  - name: edge_detector
    type: occupancy_grid
    params:
     layer: edge
     data_min: 0.0
     data_max: 1.0

  - name: walking_points
    type: point_cloud
    params:
     layer: sub_elevation

  - name: edge_line_detector
    type: occupancy_grid
    params:
     layer: edge_line
     data_min: -10.0
     data_max: 10.0

  - name: sub_map_elevation
    type: occupancy_grid
    params:
     layer: sub_elevation
     data_min: -10.0
     data_max: 10.0

  - name: sub_normals
    type: vectors
    params:
     layer_prefix: sub_normal_
     position_layer: elevation
     scale: 0.06
     line_width: 0.005
     color: 15600153
